#!/bin/bash

gen_version_string () {
	date "+0.%Y%m%d"
}

version=${1:-$(gen_version_string)}
commit=${2:-master}

[ "$version" ] || exit

pkg=check-ssh-key-$version

echo "+ Exporting git commit $commit."
git archive --prefix=$pkg/ $commit | tar xvf -

echo "+ Preparing for distribution."
(
	cd $pkg
	sed -i "s/VERSION_DEV/$version/g" configure.ac
	autoconf
)

echo "+ Building tarball."
tar -czv -f $pkg.tar.gz --exclude=autom4te.cache --exclude=.gitignore $pkg
rm -rf $pkg

